# 公共配置文件
spring:
  application:
    name: xuesi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xuesisi
    username: root
    password: 123456
    # HikariCP 连接池配置
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 10
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接超时时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 连接最大存活时间
      max-lifetime: 1200000
      # 连接测试查询
      connection-test-query: SELECT 1
      # 验证连接的频率
      validation-interval: 30000
      # 是否自动提交
      auto-commit: true
  # Redis 配置
  # todo 需替换配置，然后取消注释
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  tomcat:
    max-swallow-size: 10MB
    max-http-form-post-size: 10MB
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xuesi.xuesisi.controller

# DeepSeek 配置
deepseek:
  api-key: sk-mhvldecltnlzzjiamchmcvnducfkangmlmkpkjsxwoefdsmm # 从环境变量中获取
  model: deepseek-ai/DeepSeek-V3 # deepseek-ai/DeepSeek-R1-Distill-Qwen-7B 模型 :
  max-tokens: 4000 # 增加 token 限制以获取更详细的分析
  temperature: 0.7 # 更新为官方推荐的温度值
  api-url: https://api.siliconflow.cn/v1/chat/completions # 更新为正确的 API 端点
  connect-timeout: 10000 # 连接超时时间（毫秒）
  read-timeout: 60000 # 读取超时时间（毫秒）
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
